# AUTHORIZASTION

# Resource Server validates JWT using issuer metadata.
# Spring discovers JWKS endpoint from:
# /.well-known/openid-configuration
spring.security.oauth2.resourceserver.jwt.issuer-ur=https://idp.example.com/issuer

# Alternative manual configuration:
# jwk-set-uri: https://idp.example.com/.well-known/jwks.json


# JPA

spring.jpa.hibernate.ddl-auto=update
properties.hibernate.format_sql=true
show-sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# CONFIGURATION
spring.application.name=backend-systems-lab-stage-1
spring.profiles.active=dev

app.name=Spring Configuration Demo
app.description=Example application using YAML configuration
app.features.registration-enabled=true
app.features.experimental-ui=false
app.external-api.base-url=https://api.dev.example.com
app.external-api.api-key=dev-secret-key
app.external-api.timeout=5000