apiVersion: apps/v1
kind: Deployment
metadata:
  name: marketplace-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: marketplace-app
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: marketplace-app
    spec:
      containers:
        - name: app
          image: marketplace-modular-monolith:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: marketplace-config
            - secretRef:
                name: marketplace-secret
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 40
            periodSeconds: 20
