apiVersion: v1
kind: ConfigMap
metadata:
  name: marketplace-config
  namespace: marketplace
data:
  SPRING_PROFILES_ACTIVE: "k8s"
  SERVER_PORT: "8080"
  DATABASE_URL: "jdbc:postgresql://postgres:5432/marketplace"
  DATABASE_USERNAME: "marketplace"
  KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  EVENTS_MODE: "kafka"
  PAYMENT_GATEWAY_MODE: "fake-success"
  PAYMENT_FAKE_ACCEPT_RESERVATIONS: "true"
