package pl.jakubtworek.backend_systems_lab_stage_1.block_a.kotlin.basics.readability.java;

import java.util.List;
import java.util.Objects;

// The User class represents a domain model in Java.
// Java usually requires explicit definitions
// for constructors, getters, validation, and utility methods.
public class User {

    // Private fields encapsulate the internal state.
    private final String firstName;
    private final String lastName;
    private final int age;
    private final List<String> roles;

    // Constructor initializes all required values.
    public User(String firstName,
                String lastName,
                int age,
                List<String> roles) {

        // Validation logic is often written manually.
        if (firstName == null || firstName.isBlank()) {
            throw new IllegalArgumentException("First name cannot be empty");
        }

        if (age < 0) {
            throw new IllegalArgumentException("Age cannot be negative");
        }

        this.firstName = firstName;
        this.lastName = lastName;
        this.age = age;
        this.roles = roles;
    }

    // Explicit getter methods.
    public String getFirstName() {
        return firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public int getAge() {
        return age;
    }

    public List<String> getRoles() {
        return roles;
    }

    // Business logic method.
    public boolean isAdmin() {
        return roles.contains("ADMIN");
    }

    // Computed helper method.
    public String getFullName() {
        return firstName + " " + lastName;
    }

    // equals() is usually implemented manually
    // or generated by the IDE.
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof User)) return false;

        User user = (User) o;

        return age == user.age
                && Objects.equals(firstName, user.firstName)
                && Objects.equals(lastName, user.lastName)
                && Objects.equals(roles, user.roles);
    }

    // hashCode() must stay consistent with equals().
    @Override
    public int hashCode() {
        return Objects.hash(firstName, lastName, age, roles);
    }

    // Useful for debugging and logging.
    @Override
    public String toString() {
        return "User{" +
                "firstName='" + firstName + '\'' +
                ", lastName='" + lastName + '\'' +
                ", age=" + age +
                ", roles=" + roles +
                '}';
    }
}