package pl.jakubtworek.backend_engineering.stage_2.block_b.failure_semantics;

import org.junit.jupiter.api.Test;
import pl.jakubtworek.backend_engineering.stage_2.block_b.failure_semantics.lease.FencedRegister;
import pl.jakubtworek.backend_engineering.stage_2.block_b.failure_semantics.lease.InMemoryLeaseCoordinator;
import pl.jakubtworek.backend_engineering.stage_2.block_b.failure_semantics.lease.LeaseGrant;
import pl.jakubtworek.backend_engineering.stage_2.block_b.failure_semantics.lease.LeaseUnavailableException;
import pl.jakubtworek.backend_engineering.stage_2.block_b.failure_semantics.lease.StaleFencingTokenException;

import java.time.Clock;
import java.time.Duration;
import java.time.Instant;
import java.time.ZoneOffset;
import java.time.ZoneId;
import java.util.concurrent.atomic.AtomicReference;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

class FencingTokenTest {

    private static final Instant NOW = Instant.parse("2026-08-31T10:00:00Z");

    @Test
    void shouldRejectPausedWorkerAfterNewerOwnerHasWritten() {
        AdjustableClock clock = new AdjustableClock(NOW);
        InMemoryLeaseCoordinator coordinator = new InMemoryLeaseCoordinator(clock);
        LeaseGrant pausedWorker = coordinator.acquire("report-7", "worker-a", Duration.ofSeconds(5));

        assertThatThrownBy(() -> coordinator.acquire(
                "report-7", "worker-b", Duration.ofSeconds(5)))
                .isInstanceOf(LeaseUnavailableException.class)
                .hasMessageContaining("worker-a");

        clock.advance(Duration.ofSeconds(5));
        LeaseGrant currentWorker = coordinator.acquire("report-7", "worker-b", Duration.ofSeconds(5));
        FencedRegister<String> report = new FencedRegister<>("report-7");

        report.write(currentWorker, "generated by worker-b");

        assertThatThrownBy(() -> report.write(pausedWorker, "stale worker-a result"))
                .isInstanceOf(StaleFencingTokenException.class)
                .hasMessageContaining("1")
                .hasMessageContaining("2");
        assertThat(report.value()).contains("generated by worker-b");
        assertThat(report.lastAcceptedToken()).isEqualTo(2);
    }

    @Test
    void shouldExposeLeaseExpiryWithoutTreatingItAsSufficientWriteProtection() {
        LeaseGrant grant = new InMemoryLeaseCoordinator(Clock.fixed(NOW, ZoneOffset.UTC))
                .acquire("invoice-9", "worker-a", Duration.ofSeconds(5));

        assertThat(grant.isExpired(Clock.fixed(NOW.plusSeconds(4), ZoneOffset.UTC))).isFalse();
        assertThat(grant.isExpired(Clock.fixed(NOW.plusSeconds(5), ZoneOffset.UTC))).isTrue();
    }

    private static final class AdjustableClock extends Clock {

        private final AtomicReference<Instant> current;

        private AdjustableClock(Instant initial) {
            current = new AtomicReference<>(initial);
        }

        void advance(Duration duration) {
            current.updateAndGet(value -> value.plus(duration));
        }

        @Override
        public ZoneId getZone() {
            return ZoneOffset.UTC;
        }

        @Override
        public Clock withZone(ZoneId zone) {
            if (!ZoneOffset.UTC.equals(zone)) {
                throw new IllegalArgumentException("test clock supports UTC only");
            }
            return this;
        }

        @Override
        public Instant instant() {
            return current.get();
        }
    }
}
