package pl.jakubtworek.marketplace.integration.outbox;

import com.fasterxml.jackson.databind.ObjectMapper;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;
import pl.jakubtworek.marketplace.shared.events.ApplicationEventBus;
import pl.jakubtworek.marketplace.shared.kernel.DomainEvent;

import java.util.UUID;

@Component
public class OutboxWorker {
    private static final int DEFAULT_BATCH_SIZE = 50;

    private final OutboxEventRepository repository;
    private final ApplicationEventBus eventBus;
    private final OutboxEventMapper mapper;

    public OutboxWorker(OutboxEventRepository repository, ApplicationEventBus eventBus, ObjectMapper objectMapper) {
        this(repository, eventBus, new OutboxEventMapper(objectMapper));
    }

    public OutboxWorker(OutboxEventRepository repository, ApplicationEventBus eventBus, OutboxEventMapper mapper) {
        this.repository = repository;
        this.eventBus = eventBus;
        this.mapper = mapper;
    }

    @Scheduled(fixedDelayString = "${marketplace.outbox.worker-delay-ms:5000}")
    public void scheduledPublish() {
        publishNew(DEFAULT_BATCH_SIZE);
    }

    @Transactional
    public int publishNew(int limit) {
        var events = repository.findNew(limit);
        events.forEach(this::publishOneSafely);
        return events.size();
    }

    @Transactional
    public int retryFailed(int limit) {
        var events = repository.findFailed(limit);
        events.forEach(this::publishOneSafely);
        return events.size();
    }

    @Transactional
    public void retryManually(UUID outboxEventId) {
        repository.markNewForRetry(outboxEventId);
        publishById(outboxEventId);
    }

    @Transactional
    public void publishById(UUID outboxEventId) {
        OutboxEvent event = repository.findById(outboxEventId)
                .orElseThrow(() -> new IllegalArgumentException("Outbox event not found: " + outboxEventId));
        if (event.status() == OutboxEventStatus.PUBLISHED) {
            return;
        }
        publishOneSafely(event);
    }

    /**
     * Test/development helper: keeps draining NEW events generated by handlers until the outbox is idle.
     */
    public int publishUntilIdle(int batchSize, int maxIterations) {
        int total = 0;
        for (int i = 0; i < maxIterations; i++) {
            int published = publishNew(batchSize);
            total += published;
            if (published == 0) {
                return total;
            }
        }
        throw new IllegalStateException("Outbox is still producing new events after " + maxIterations + " iterations");
    }

    private void publishOneSafely(OutboxEvent outboxEvent) {
        try {
            DomainEvent domainEvent = mapper.toDomainEvent(outboxEvent);
            eventBus.publish(domainEvent);
            repository.markPublished(outboxEvent.id());
        } catch (Exception e) {
            repository.markFailed(outboxEvent.id(), e.getMessage());
        }
    }
}
