spring:
  application:
    name: catalog-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/catalog}
    username: ${SPRING_DATASOURCE_USERNAME:app}
    password: ${SPRING_DATASOURCE_PASSWORD:app}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}

server:
  port: ${SERVER_PORT:8081}

app:
  cache:
    events:
      ttl: ${CACHE_EVENTS_TTL:60s}
    event-details:
      ttl: ${CACHE_EVENT_DETAILS_TTL:120s}
    availability:
      ttl: ${CACHE_AVAILABILITY_TTL:10s}

management:
  tracing:
    sampling:
      probability: ${MANAGEMENT_TRACING_SAMPLING_PROBABILITY:1.0}
  otlp:
    tracing:
      endpoint: ${MANAGEMENT_OTLP_TRACING_ENDPOINT:http://localhost:4318/v1/traces}
  observations:
    key-values:
      service.name: ${spring.application.name}
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics,caches
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  level:
    root: ${LOG_LEVEL:INFO}
