package com.example.paymentsystem.payment;

public enum PaymentStatus {
    CREATED, PENDING, AUTHORIZED, CAPTURED, SUCCEEDED, PARTIALLY_REFUNDED, REFUNDED, FAILED, CANCELED, CHARGEBACK_OPENED, CHARGEBACK_LOST, CHARGEBACK_WON
}
