spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/chat_stage1
    username: chat
    password: chat
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
