apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-api-data
spec:
  # ReadWriteOnce means the volume can be mounted as read-write by a single node.
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi