package com.example.notification.domain;

public enum AuditAction {
    NOTIFICATION_CREATED,
    NOTIFICATION_DUPLICATE_RETURNED,
    NOTIFICATION_CANCELLED,
    JOB_QUEUED,
    JOB_SENT,
    JOB_RETRY_SCHEDULED,
    JOB_FAILED,
    JOB_DELIVERED,
    JOB_BOUNCED,
    OUTBOX_PUBLISHED,
    TEMPLATE_CREATED,
    TEMPLATE_UPDATED,
    TEMPLATE_DELETED,
    PREFERENCES_UPDATED,
    RATE_LIMIT_REJECTED,
    CAMPAIGN_CREATED,
    CAMPAIGN_STARTED,
    CAMPAIGN_COMPLETED,
    DIGEST_BUFFERED,
    DIGEST_FLUSHED,
    ARCHIVE_RUN
}
