apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-api
  labels:
    app: demo-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-api

  strategy:
    type: RollingUpdate
    rollingUpdate:
      # Keep all current replicas available during rollout.
      maxUnavailable: 0

      # Allow one extra Pod during rollout.
      maxSurge: 1

  template:
    metadata:
      labels:
        app: demo-api
    spec:
      # The application does not need Kubernetes API access.
      automountServiceAccountToken: false

      terminationGracePeriodSeconds: 30

      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault

      containers:
        - name: app
          image: demo-api-workshop:dev

          # Important for kind local workflow after kind load docker-image.
          imagePullPolicy: IfNotPresent

          ports:
            - name: http
              containerPort: 8080

          env:
            - name: BIND_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: demo-api-config
                  key: BIND_ADDRESS

            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: demo-api-config
                  key: PORT

            - name: APP_NAME
              valueFrom:
                configMapKeyRef:
                  name: demo-api-config
                  key: APP_NAME

            - name: STARTUP_DELAY
              valueFrom:
                configMapKeyRef:
                  name: demo-api-config
                  key: STARTUP_DELAY

            - name: IMAGE_TAG
              valueFrom:
                configMapKeyRef:
                  name: demo-api-config
                  key: IMAGE_TAG

            - name: COMMIT_SHA
              valueFrom:
                configMapKeyRef:
                  name: demo-api-config
                  key: COMMIT_SHA

          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

          startupProbe:
            httpGet:
              path: /startupz
              port: http
            periodSeconds: 5
            failureThreshold: 12
            timeoutSeconds: 2

          readinessProbe:
            httpGet:
              path: /readyz
              port: http
            periodSeconds: 5
            failureThreshold: 2
            timeoutSeconds: 2

          livenessProbe:
            httpGet:
              path: /livez
              port: http
            periodSeconds: 10
            failureThreshold: 3
            timeoutSeconds: 2

          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL