spring:
  application:
    name: reservation-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5434/reservation}
    username: ${SPRING_DATASOURCE_USERNAME:app}
    password: ${SPRING_DATASOURCE_PASSWORD:app}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

server:
  port: ${SERVER_PORT:8082}

services:
  catalog:
    url: ${CATALOG_SERVICE_URL:http://localhost:8081}

app:
  http-client:
    connect-timeout-ms: ${HTTP_CLIENT_CONNECT_TIMEOUT_MS:1000}
    response-timeout-ms: ${HTTP_CLIENT_RESPONSE_TIMEOUT_MS:2500}

resilience4j:
  circuitbreaker:
    instances:
      catalog:
        sliding-window-size: 20
        minimum-number-of-calls: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
  retry:
    instances:
      catalog:
        max-attempts: 2
        wait-duration: 200ms
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics,circuitbreakers,retries
  metrics:
    tags:
      application: ${spring.application.name}
