server:
  port: 8080

spring:
  application:
    name: news-feed-stage-1

  datasource:
    url: jdbc:postgresql://localhost:5432/news_feed
    username: news_feed
    password: news_feed
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        format_sql: false

  flyway:
    enabled: true
